#!/usr/bin/env bash
#
# NixOS Router Installation Script
#
# This script handles fresh installation of the NixOS router configuration.
# Run from a NixOS live ISO with this repository cloned.
#
# Usage:
#   sudo ./install.sh
#
# Prerequisites:
#   - Booted into NixOS live ISO
#   - Repository cloned to a working directory
#   - Three+ network interfaces available (WAN + trunk + wired LAN)

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

info() { echo -e "${BLUE}[INFO]${NC} $*"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $*"; }
error() { echo -e "${RED}[ERROR]${NC} $*" >&2; }
success() { echo -e "${GREEN}[OK]${NC} $*"; }

# Check if running as root
check_root() {
    if [[ $EUID -ne 0 ]]; then
        error "This script must be run as root"
        exit 1
    fi
}

# Get script directory (where nixrouter repo is)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Ensure required tools are available, fetching via nix if missing
ensure_deps() {
    local missing=()
    local nixpkgs=()

    # command -> nixpkgs attribute
    declare -A dep_map=(
        [age]=age
    )

    for cmd in "${!dep_map[@]}"; do
        if ! command -v "$cmd" &>/dev/null; then
            missing+=("$cmd")
            nixpkgs+=("nixpkgs#${dep_map[$cmd]}")
        fi
    done

    if [[ ${#missing[@]} -gt 0 ]]; then
        info "Fetching missing tools via nix: ${missing[*]}"
        # Re-exec the script inside nix shell with the missing packages
        # Use absolute path for $0 so nix doesn't interpret it as a flake ref
        exec nix --experimental-features 'nix-command flakes' shell "${nixpkgs[@]}" --command "$(readlink -f "$0")" "$@"
    fi
}

# List available network interfaces (excluding lo and virtual)
list_interfaces() {
    ip -o link show | awk -F': ' '{print $2}' | grep -v '^lo$' | grep -v '^vir' | grep -v '@'
}

# Select an interface from the list
select_interface() {
    local prompt="$1"
    local exclude="$2"
    local interfaces

    mapfile -t interfaces < <(list_interfaces | grep -vE "^(${exclude})$")

    if [[ ${#interfaces[@]} -eq 0 ]]; then
        error "No interfaces available"
        exit 1
    fi

    echo "" >&2
    info "$prompt" >&2
    echo "" >&2

    local i=1
    for iface in "${interfaces[@]}"; do
        # Get MAC and state for context
        local mac state
        mac=$(ip link show "$iface" | grep -oP 'link/ether \K[^ ]+' || echo "N/A")
        state=$(ip link show "$iface" | grep -oP 'state \K[^ ]+' || echo "UNKNOWN")
        printf "  %d) %-15s MAC: %-17s State: %s\n" "$i" "$iface" "$mac" "$state" >&2
        ((i++))
    done

    echo "" >&2
    while true; do
        read -rp "Selection [1-${#interfaces[@]}]: " selection
        if [[ "$selection" =~ ^[0-9]+$ ]] && ((selection >= 1 && selection <= ${#interfaces[@]})); then
            echo "${interfaces[$((selection-1))]}"
            return
        fi
        warn "Invalid selection, try again"
    done
}

# Select installation disk
select_disk() {
    local disks
    mapfile -t disks < <(lsblk -dno NAME,SIZE,MODEL | grep -E '^(sd|nvme|vd)' | awk '{print "/dev/"$1}')

    if [[ ${#disks[@]} -eq 0 ]]; then
        error "No disks found"
        exit 1
    fi

    echo "" >&2
    info "Select installation disk:" >&2
    warn "WARNING: This will ERASE ALL DATA on the selected disk!" >&2
    echo "" >&2

    local i=1
    for disk in "${disks[@]}"; do
        local size model
        size=$(lsblk -dno SIZE "$disk")
        model=$(lsblk -dno MODEL "$disk" | xargs)
        printf "  %d) %-12s %8s  %s\n" "$i" "$disk" "$size" "$model" >&2
        ((i++))
    done

    echo "" >&2
    while true; do
        read -rp "Selection [1-${#disks[@]}]: " selection
        if [[ "$selection" =~ ^[0-9]+$ ]] && ((selection >= 1 && selection <= ${#disks[@]})); then
            echo "${disks[$((selection-1))]}"
            return
        fi
        warn "Invalid selection, try again"
    done
}

# Write interfaces.nix
write_interfaces() {
    local wan="$1"
    local lan="$2"
    local wired_lan="$3"
    local target="$SCRIPT_DIR/hosts/router/interfaces.nix"

    info "Writing interface configuration to $target"

    cat > "$target" << EOF
# Network interface configuration
#
# Generated by install.sh on $(date -Iseconds)
# WAN: connects to ISP/modem
# Trunk: connects to AP (carries 802.1Q VLANs + untagged)
# Wired LAN: connects to unmanaged switch

{
  wan = "$wan";
  lan = "$lan";
  wiredLan = "$wired_lan";
}
EOF
    success "Interface configuration written"
}

# Decrypt age key
decrypt_age_key() {
    local target="$1"
    local encrypted="$SCRIPT_DIR/secrets/age-key.enc"

    if [[ ! -f "$encrypted" ]]; then
        error "Encrypted age key not found: $encrypted"
        exit 1
    fi

    info "Decrypting age key..."

    mkdir -p "$(dirname "$target")"

    # Read passphrase explicitly from /dev/tty since stdin may be
    # exhausted by earlier commands (e.g. nix run disko)
    local passphrase
    read -rsp "Enter passphrase for age key: " passphrase < /dev/tty
    echo "" >&2

    if ! echo "$passphrase" | age -d "$encrypted" > "$target"; then
        error "Failed to decrypt age key"
        exit 1
    fi

    chmod 600 "$target"
    success "Age key decrypted to $target"
}

# Run disko to partition and format disk
run_disko() {
    local disk="$1"

    info "Running disko to partition $disk..."
    warn "This will ERASE ALL DATA on $disk"

    read -rp "Type 'yes' to confirm: " confirm
    if [[ "$confirm" != "yes" ]]; then
        error "Aborted by user"
        exit 1
    fi

    # Run disko in disko mode (partition + format + mount)
    # Redirect stdin from /dev/null to prevent nix from consuming terminal input
    nix --experimental-features 'nix-command flakes' run \
        github:nix-community/disko -- \
        --mode disko \
        "$SCRIPT_DIR/hosts/router/disko.nix" \
        --arg device "\"$disk\"" < /dev/null

    success "Disk partitioned and mounted"
}

# Run nixos-install
run_install() {
    info "Installing NixOS..."

    # Copy the repo to the new system's persist location
    mkdir -p /mnt/nix/persist/etc
    cp -r "$SCRIPT_DIR" /mnt/nix/persist/etc/nixos

    # Install NixOS
    nixos-install --flake "$SCRIPT_DIR#router" --no-root-passwd

    success "NixOS installed successfully"
}

# Main installation flow
main() {
    echo ""
    echo "=========================================="
    echo "    NixOS Router Installation Script"
    echo "=========================================="
    echo ""

    check_root
    ensure_deps "$@"

    # Check we're on NixOS live ISO
    if [[ ! -d /mnt ]] || mountpoint -q /mnt 2>/dev/null; then
        warn "Target /mnt appears to be mounted already"
        read -rp "Continue anyway? [y/N]: " cont
        [[ "$cont" =~ ^[Yy]$ ]] || exit 1
    fi

    # Interface selection
    info "Detecting network interfaces..."
    echo ""
    list_interfaces | while read -r iface; do
        local mac state
        mac=$(ip link show "$iface" | grep -oP 'link/ether \K[^ ]+' || echo "N/A")
        state=$(ip link show "$iface" | grep -oP 'state \K[^ ]+' || echo "UNKNOWN")
        printf "  %-15s MAC: %-17s State: %s\n" "$iface" "$mac" "$state"
    done

    wan=$(select_interface "Select WAN interface (connects to ISP/modem):" "")
    success "WAN: $wan"

    lan=$(select_interface "Select trunk interface (connects to AP, carries VLANs):" "$wan")
    success "Trunk: $lan"

    wired_lan=$(select_interface "Select wired LAN interface (connects to unmanaged switch):" "$wan|$lan")
    success "Wired LAN: $wired_lan"

    # Write interfaces.nix
    write_interfaces "$wan" "$lan" "$wired_lan"

    # Disk selection
    disk=$(select_disk)
    success "Disk: $disk"

    # Summary
    echo ""
    echo "=========================================="
    echo "  Installation Summary"
    echo "=========================================="
    echo "  WAN Interface:       $wan"
    echo "  Trunk Interface:     $lan"
    echo "  Wired LAN Interface: $wired_lan"
    echo "  Target Disk:         $disk"
    echo "=========================================="
    echo ""

    read -rp "Proceed with installation? [y/N]: " proceed
    if [[ ! "$proceed" =~ ^[Yy]$ ]]; then
        error "Aborted by user"
        exit 1
    fi

    # Partition disk
    run_disko "$disk"

    # Decrypt age key to persist location
    decrypt_age_key "/mnt/nix/persist/var/lib/sops-nix/key.txt"

    # Install NixOS
    run_install

    echo ""
    success "Installation complete!"
    echo ""
    info "Next steps:"
    echo "  1. Reboot into the new system"
    echo "  2. Connect WAN ($wan) to your modem/ISP"
    echo "  3. Connect trunk ($lan) to your wireless AP"
    echo "  4. Connect wired LAN ($wired_lan) to your unmanaged switch"
    echo "  5. SSH to admin@10.0.0.1 from the LAN"
    echo ""

    read -rp "Reboot now? [y/N]: " reboot
    if [[ "$reboot" =~ ^[Yy]$ ]]; then
        info "Rebooting..."
        reboot
    fi
}

main "$@"
