# Network interface configuration
#
# This file is generated by install.sh based on hardware detection.
# Do not edit manually unless you know your interface names.
#
# To find interface names: ip link

{
  wan = "eth0";  # WAN interface (connects to ISP/modem)
  lan = "eth1";  # LAN interface (connects to local network/switch)
}
