# Network interface configuration
#
# This file is generated by install.sh based on hardware detection.
# Do not edit manually unless you know your interface names.
#
# To find interface names: ip link

{
  wan = "enp3s0f0";      # WAN interface (connects to ISP/modem)
  lan = "enp4s0f0";      # Trunk interface (connects to AP, carries VLANs + untagged)
  wiredLan = "enp3s0f1"; # Wired LAN interface (connects to unmanaged switch)
}
